// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANRNbPeLKaztd_Lv03DHNETytYrXhJPtY',
    appId: '1:522849586818:web:b438e1d03e5def19722e9b',
    messagingSenderId: '522849586818',
    projectId: 'odoo-combat-91a95',
    authDomain: 'odoo-combat-91a95.firebaseapp.com',
    storageBucket: 'odoo-combat-91a95.appspot.com',
    measurementId: 'G-4Y3GRELMRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9776h53ulNef9W6onlzYNrhj3dIm_AI',
    appId: '1:522849586818:android:282be5c96713891c722e9b',
    messagingSenderId: '522849586818',
    projectId: 'odoo-combat-91a95',
    storageBucket: 'odoo-combat-91a95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD52iMTCpwVFkpuC8XwR9r6iaPXrDAksdE',
    appId: '1:522849586818:ios:2e6acbd0ad52aa25722e9b',
    messagingSenderId: '522849586818',
    projectId: 'odoo-combat-91a95',
    storageBucket: 'odoo-combat-91a95.appspot.com',
    iosBundleId: 'com.example.odooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD52iMTCpwVFkpuC8XwR9r6iaPXrDAksdE',
    appId: '1:522849586818:ios:2e6acbd0ad52aa25722e9b',
    messagingSenderId: '522849586818',
    projectId: 'odoo-combat-91a95',
    storageBucket: 'odoo-combat-91a95.appspot.com',
    iosBundleId: 'com.example.odooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANRNbPeLKaztd_Lv03DHNETytYrXhJPtY',
    appId: '1:522849586818:web:b469e18ff2d29b95722e9b',
    messagingSenderId: '522849586818',
    projectId: 'odoo-combat-91a95',
    authDomain: 'odoo-combat-91a95.firebaseapp.com',
    storageBucket: 'odoo-combat-91a95.appspot.com',
    measurementId: 'G-W1SYWCL17Z',
  );
}
