# Generated by Django 3.2.8 on 2024-06-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('description3', models.CharField(max_length=200)),
                ('image1', models.ImageField(null=True, upload_to='blog-images/')),
                ('image2', models.ImageField(null=True, upload_to='blog-images/')),
                ('image3', models.ImageField(null=True, upload_to='blog-images/')),
            ],
        ),
    ]
