# Generated by Django 3.2.8 on 2024-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='isBasicDetails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
