# Generated by Django 3.2.8 on 2024-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240629_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('contactno', models.CharField(max_length=13)),
                ('businessname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('bankaccountname', models.CharField(max_length=200)),
                ('bankaccountno', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='recycler-images/')),
            ],
        ),
    ]
