# Generated by Django 3.2.8 on 2024-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recycler'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('pdf', models.FileField(null=True, upload_to='invoice/')),
            ],
        ),
    ]
